name: style_generator
description: "Theme and Style generator. Generates ThemeExtension files"
version: 0.2.3
repository: https://github.com/YukiAttano/style_generator/tree/main/style_generator
issue_tracker: https://github.com/YukiAttano/style_generator/issues
topics:
  - theme
  - style
  - extension
  - codegen

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  style_generator_annotation: ^0.1.3
  #  path: "../style_generator_annotation"

  logging: ^1.0.0

  collection: ^1.0.0 # ^1.19.1

  path: ^1.0.0 # ^1.9.1

  meta: ^1.0.0
  build: ">=3.0.0 <5.0.0"
  analyzer: ">=8.1.0 <11.0.0"
  build_config: ^1.0.0
  dart_style: ^3.0.0 # ^3.1.2

dev_dependencies:
  lints: ">=5.0.0 <8.0.0"
  build_runner: ^2.0.0 #^2.9.0

