name: style_generator_annotation
description: "The Annotations for style_generator to generate ThemeExtensions"
version: 0.1.6
repository: https://github.com/YukiAttano/style_generator/tree/main/style_generator_annotation
issue_tracker: https://github.com/YukiAttano/style_generator/issues
topics:
  - theme
  - style
  - copy-with
  - extension
  - codegen

resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  meta: ^1.15.0

dev_dependencies:
  lints: ">=5.0.0 <8.0.0"
  improved_analysis: ^1.0.0
